steps:
  # Step 1: Build the JAR file using Maven
  - name: 'maven:3.6.3-jdk-11' # Use the appropriate Maven image and JDK version
    entrypoint: 'mvn'
    args: ['clean', 'package']
  
  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/gcpspringbootdocker/gcpspringboot/gcpspringbootdocker:latest', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/gcpspringbootdocker/gcpspringboot/gcpspringbootdocker:latest']

images:
  - 'asia-south1-docker.pkg.dev/gcpspringbootdocker/gcpspringboot/gcpspringbootdocker:latest'
  
options:
  logging: CLOUD_LOGGING_ONLY
